### ISSUE TITLE
schemat glowny

### ISSUE THREAD

**Issue by mac923** [korkosz/Vesta_v2#4]
![vesta](https://cloud.githubusercontent.com/assets/18197674/14190315/63b1f006-f792-11e5-83c7-d216f1459144.jpg)

**Comment by korkosz** [comment]
## Lista: moje otwarte zgloszenia
- [ ] nazwa taska - anchor
- [ ] priorytet
- [ ] status

**Comment by mac923** [comment]
- [ ] korek ma maly worek
